import asyncio
import json
import logging
import httpx
from typing import Awaitable, Callable

from azure.identity.aio import DefaultAzureCredential
from azure.servicebus.aio import ServiceBusClient
from azure.servicebus.exceptions import ServiceBusError

from app.core.config import settings
from app.service.assignment_service import AssignmentService
from app.repository.other_event_repository import OtherEventRepository

log = logging.getLogger(__name__)

EventHandler = Callable[[dict], Awaitable[None]]

async def _handle_user_deleted(envelope: dict) -> None:
    event_data = envelope
    event_id = envelope["event_id"]
    
    repo = OtherEventRepository()
    if repo.exists(event_id):
        return
        
    service = AssignmentService()
    user_assignments = service.get_assignments_by_creator_id(event_data["id"])
    for assignment in user_assignments:
        try:
            await service.delete_assignment(assignment.id)
        except Exception:
            pass
    repo.create(event_id)

async def _handle_internal_deadline(envelope: dict) -> None:
    """Consumes the scheduled messages generated by task_client.py"""
    event_data = envelope
    url_path = event_data.get("url_path", "")
    payload = event_data.get("payload", {})

    # Execute the local HTTP call that Cloud Tasks was doing originally
    async with httpx.AsyncClient() as client:
        await client.post(f"http://localhost:8000{url_path}", json=payload)

HANDLERS: dict[str, EventHandler] = {
    "user.deleted": _handle_user_deleted,
    "internal.deadline_reached": _handle_internal_deadline,
}

async def _dispatch(envelope: dict) -> None:
    event_type = envelope.get("event_type")
    # For internal scheduled events, application properties handles routing
    if not event_type and "url_path" in envelope and "payload" in envelope:
         event_type = "internal.deadline_reached"

    handler = HANDLERS.get(event_type)
    if handler is None:
        return
    await handler(envelope)

async def run_consumer(topic_name: str, stop_event: asyncio.Event) -> None:
    cred = DefaultAzureCredential()
    backoff = 1.0
    while not stop_event.is_set():
        try:
            async with ServiceBusClient(
                fully_qualified_namespace=settings.service_bus_namespace,
                credential=cred,
            ) as client:
                receiver = client.get_subscription_receiver(
                    topic_name=topic_name,
                    subscription_name=settings.service_bus_subscription,
                    max_wait_time=5,
                )
                async with receiver:
                    backoff = 1.0
                    while not stop_event.is_set():
                        msgs = await receiver.receive_messages(max_message_count=10, max_wait_time=5)
                        for msg in msgs:
                            try:
                                envelope = json.loads(b"".join(msg.body).decode("utf-8"))
                                await _dispatch(envelope)
                                await receiver.complete_message(msg)
                            except Exception:
                                log.exception("Handler failed; abandoning message")
                                await receiver.abandon_message(msg)
        except ServiceBusError:
            await asyncio.sleep(backoff)
            backoff = min(backoff * 2, 60)
        except asyncio.CancelledError:
            break
    await cred.close()