swagger: "2.0"
info:
  title: "Assignments API"
  description: "API Gateway for Users and Assignments Microservices"
  version: "1.0.0"

# This defines the JWT security scheme
securityDefinitions:
  user_auth:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    # Replace with your actual Issuer URL (e.g., from Firebase or your Users service)
    x-google-issuer: "https://users-service-1088240463128.europe-west1.run.app"
    x-google-jwks_uri: "https://users-service-1088240463128.europe-west1.run.app/jwks"
    x-google-audiences: "cloudcomputing-491711"

paths:
  # --- Users Service (No JWT required for login/signup) ---
  /users/**:
    get:
      x-google-backend:
        address: "https://users-service-1088240463128.europe-west1.run.app"
        jwt_audience: "https://users-service-1088240463128.europe-west1.run.app"
      operationId: "getUsers"
      security: []
      responses:
        200:
          description: "OK"
    post:
      x-google-backend:
        address: "https://users-service-1088240463128.europe-west1.run.app"
        jwt_audience: "https://users-service-1088240463128.europe-west1.run.app"
      operationId: "createUser"
      security: []
      responses:
        201:
          description: "Created"
    delete:
      x-google-backend:
        address: "https://users-service-1088240463128.europe-west1.run.app"
        jwt_audience: "https://users-service-1088240463128.europe-west1.run.app"
      operationId: "deleteUser"
      security:
        - user_auth: []
      responses:
        204:
          description: "Deleted"
    patch:
      x-google-backend:
        address: "https://users-service-1088240463128.europe-west1.run.app"
        jwt_audience: "https://users-service-1088240463128.europe-west1.run.app"
      operationId: "updateUser"
      security:
        - user_auth: []
      responses:
        200:
          description: "Updated"

  # --- Assignments Service (JWT Protected) ---
  # /assignments/**:
  #   get:
  #     operationId: "getAssignments"
  #     security:
  #       - user_auth: []
  #     x-google-backend:
  #       address: https://assignments-service-hash.a.run.app
  #     responses:
  #       200:
  #         description: "OK"
  #   post:
  #     operationId: "createAssignment"
  #     security:
  #       - user_auth: []
  #     x-google-backend:
  #       address: https://assignments-service-hash.a.run.app
  #     responses:
  #       201:
  #         description: "Created"
  #   delete:
  #     operationId: "deleteAssignment"
  #     security:
  #       - user_auth: []
  #     x-google-backend:
  #       address: https://assignments-service-hash.a.run.app
  #     responses:
  #       204:
  #         description: "Deleted"
  #   patch:
  #     operationId: "updateAssignment"
  #     security:
  #       - user_auth: []
  #     x-google-backend:
  #       address: https://assignments-service-hash.a.run.app
  #     responses:
  #       200:
  #         description: "Updated"