SET SERVEROUTPUT ON;
ALTER SESSION SET CONTAINER=PDBCONTREST;
DROP USER CONTREST CASCADE;

CREATE USER CONTREST IDENTIFIED BY CONTREST DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

ALTER USER CONTREST QUOTA 100M ON USERS;

GRANT CREATE SESSION TO CONTREST;
GRANT CONNECT TO CONTREST;
GRANT RESOURCE TO CONTREST;
GRANT CREATE TABLE TO CONTREST;
GRANT CREATE VIEW TO CONTREST;
GRANT CREATE SEQUENCE TO CONTREST;
GRANT CREATE TRIGGER TO CONTREST;
GRANT CREATE SYNONYM TO CONTREST;
GRANT CREATE PROCEDURE TO CONTREST;
GRANT CREATE ANY DIRECTORY TO CONTREST;
GRANT CREATE TYPE TO CONTREST;
GRANT SELECT_CATALOG_ROLE TO CONTREST;
GRANT EXECUTE_CATALOG_ROLE TO CONTREST;