SET SERVEROUTPUT ON;

DROP SEQUENCE CONTESTS_ID_SEQ;
DROP SEQUENCE CONTESTANTS_ID_SEQ;
DROP SEQUENCE PRIZES_ID_SEQ;

CREATE SEQUENCE CONTESTS_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE;
CREATE SEQUENCE CONTESTANTS_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE;
CREATE SEQUENCE PRIZES_ID_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCYCLE;
